// Bundles the third-party document libraries into vendor/docs.js (ESM) and vendor/intake-runtime.js (IIFE).
// Run with `npm run build:vendor`. Outputs are committed so the site deploys with no build step.
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url)));
const versions = {};
for (const name of ['docxtemplater', 'pizzip', 'docx-preview', 'jszip']) {
  versions[name] = JSON.parse(readFileSync(new URL(`../node_modules/${name}/package.json`, import.meta.url))).version;
}
const banner = `/* Clausery vendored document engine. Bundled from: ${Object.entries(versions).map(([k, v]) => `${k}@${v}`).join(', ')}.
   Licenses: docxtemplater (MIT), pizzip (MIT), jszip (MIT), docx-preview (Apache-2.0). Rebuild with \`npm run build:vendor\`. */`;

await build({
  entryPoints: ['src/vendor-entry.js'],
  bundle: true,
  format: 'esm',
  minify: true,
  sourcemap: false,
  target: ['es2020'],
  outfile: 'vendor/docs.js',
  alias: { lodash: './src/shims/lodash.js' },
  banner: { js: banner },
  legalComments: 'none',
  logLevel: 'info',
});

// The intake runtime is inlined into exported client intake forms; it must be a single self-contained script.
await build({
  entryPoints: ['src/intake/runtime.js'],
  bundle: true,
  format: 'iife',
  globalName: 'ClauseryIntake',
  minify: true,
  target: ['es2020'],
  outfile: 'vendor/intake-runtime.js',
  banner: { js: `/* Clausery intake runtime v${pkg.version}. Inlined into exported intake forms. */` },
  legalComments: 'none',
  logLevel: 'info',
});
writeFileSync('vendor/VERSIONS.json', JSON.stringify({ app: pkg.version, ...versions }, null, 2) + '\n');
writeFileSync('app/lib/versions.js', `/* Generated by tools/build-vendor.mjs; do not edit. */\nexport const VERSIONS = ${JSON.stringify({ app: pkg.version, ...versions })};\n`);
