// Generates the sample .docx templates shipped in samples/ (run with `npm run build:samples`).
// Each template uses plain docxtemplater tags: {field}, {#section}...{/section}, {^section}...{/section}, {#list}{item}{/list}.
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { writeFileSync, mkdirSync } from 'node:fs';
import JSZip from 'jszip';

// Fixed timestamps make the output byte-for-byte reproducible, so rebuilding never dirties the tracked samples.
const FIXED_DATE = new Date('2026-09-24T00:00:00Z');
async function deterministic(buffer) {
  const src = await JSZip.loadAsync(buffer);
  const out = new JSZip();
  for (const name of Object.keys(src.files).sort()) {
    const entry = src.files[name];
    if (entry.dir) continue;
    let data = await entry.async('nodebuffer');
    if (name === 'docProps/core.xml') data = Buffer.from(data.toString('utf8').replace(/(<dcterms:(?:created|modified)[^>]*>)[^<]*(<\/dcterms:)/g, '$1' + FIXED_DATE.toISOString().replace(/\.\d+Z$/, 'Z') + '$2'));
    out.file(name, data, { date: FIXED_DATE, createFolders: false });
  }
  return out.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', platform: 'UNIX' });
}

const P = (text, opts = {}) => new Paragraph({ children: [new TextRun({ text, ...opts })], spacing: { after: 160 } });
const H = (text) => new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 240, after: 160 } });
const H2 = (text) => new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 120 } });
const Title = (text) => new Paragraph({ text, heading: HeadingLevel.TITLE, alignment: AlignmentType.CENTER, spacing: { after: 240 } });
const Numbered = (text) => new Paragraph({ children: [new TextRun(text)], numbering: { reference: 'clauses', level: 0 }, spacing: { after: 120 } });
const Bullet = (text) => new Paragraph({ children: [new TextRun(text)], bullet: { level: 0 }, spacing: { after: 80 } });

function doc(children) {
  return new Document({
    creator: 'Clausery', description: 'Clausery sample template',
    numbering: { config: [{ reference: 'clauses', levels: [{ level: 0, format: 'decimal', text: '%1.', alignment: AlignmentType.START }] }] },
    styles: { default: { document: { run: { font: 'Calibri', size: 22 } } } },
    sections: [{ properties: {}, children }],
  });
}

const nda = doc([
  Title('MUTUAL NON-DISCLOSURE AGREEMENT'),
  P('This Mutual Non-Disclosure Agreement (the "Agreement") is entered into on {effective_date} between {party_a_name}, a {party_a_entity} with its principal place of business at {party_a_address} ("{party_a_short}"), and {party_b_name}, a {party_b_entity} with its principal place of business at {party_b_address} ("{party_b_short}"). Each is a "Party" and together the "Parties".'),
  H('1. Purpose'),
  P('The Parties wish to explore {purpose} (the "Purpose") and, in connection with the Purpose, each Party may disclose Confidential Information to the other.'),
  H('2. Confidential Information'),
  P('"Confidential Information" means all non-public information disclosed by either Party in connection with the Purpose, whether disclosed orally, in writing or by inspection, that is designated as confidential or that reasonably should be understood to be confidential.'),
  P('{#has_carveouts}Confidential Information does not include information that: (a) is or becomes publicly available through no fault of the receiving Party; (b) was rightfully known to the receiving Party before disclosure; (c) is independently developed without use of the disclosing Party\'s Confidential Information; or (d) is rightfully obtained from a third party without restriction.{/has_carveouts}'),
  H('3. Obligations'),
  Numbered('The receiving Party shall use the Confidential Information solely for the Purpose.'),
  Numbered('The receiving Party shall protect the Confidential Information using at least the same degree of care it uses for its own confidential information, and no less than reasonable care.'),
  Numbered('The receiving Party shall restrict disclosure to those of its employees and advisers who need to know and who are bound by obligations at least as protective as this Agreement.'),
  H('4. Term'),
  P('This Agreement is effective from the date first written above and continues for {term_years} years. The obligations of confidentiality survive for {survival_years} years after expiry or termination.'),
  H('5. Governing Law'),
  P('This Agreement is governed by the laws of {governing_law}. {#has_jurisdiction}The courts of {jurisdiction} have exclusive jurisdiction over any dispute arising out of this Agreement.{/has_jurisdiction}'),
  H('6. Notices'),
  P('Notices must be sent to the addresses above{#has_notice_email} and copied by email to {party_a_email} and {party_b_email}{/has_notice_email}.'),
  H('Signatures'),
  P('{party_a_name}'), P('By: ____________________________'), P('Name: {party_a_signatory}'), P('Title: {party_a_signatory_title}'),
  P(''),
  P('{party_b_name}'), P('By: ____________________________'), P('Name: {party_b_signatory}'), P('Title: {party_b_signatory_title}'),
]);

const engagement = doc([
  Title('ENGAGEMENT LETTER'),
  P('{letter_date}'),
  P('{client_name}'), P('{client_address}'),
  P('Re: {matter_description}'),
  P('Dear {client_salutation},'),
  P('Thank you for choosing {firm_name} (the "Firm") to represent you. This letter confirms the terms of our engagement.'),
  H2('Scope of services'),
  P('The Firm will represent {client_name} in connection with {matter_description} (the "Matter"). Our engagement is limited to the Matter and does not include any other legal work unless agreed in writing.'),
  H2('Team'),
  P('The following attorneys are expected to work on the Matter:'),
  new Paragraph({ children: [new TextRun('{#attorneys}')] }),
  Bullet('{name}, {role} — {rate} per hour'),
  new Paragraph({ children: [new TextRun('{/attorneys}')] }),
  H2('Fees'),
  P('{#fee_hourly}Our fees are based on the time spent on the Matter at the hourly rates listed above, billed in increments of one tenth of an hour.{/fee_hourly}{#fee_flat}Our fee for the Matter is a flat fee of {flat_fee}, payable {flat_fee_terms}.{/fee_flat}'),
  P('{#has_retainer}Before we begin work, we require an advance fee deposit (retainer) of {retainer_amount}, which will be held in our client trust account and applied to invoices as they are issued.{/has_retainer}{^has_retainer}No advance deposit is required for this Matter.{/has_retainer}'),
  H2('Costs and billing'),
  P('You agree to reimburse the Firm for costs incurred on your behalf, including filing fees, court reporter fees and travel. Invoices are issued monthly and are due within {payment_days} days.'),
  H2('Termination'),
  P('You may terminate this engagement at any time by written notice. The Firm may withdraw as permitted by the applicable rules of professional conduct.'),
  P('If these terms are acceptable, please sign and return a copy of this letter.'),
  P('Sincerely,'), P('{responsible_attorney}'), P('{firm_name}'),
  P(''),
  P('AGREED AND ACCEPTED:'), P('____________________________'), P('{client_name}'), P('Date: ______________'),
]);

const offer = doc([
  Title('OFFER OF EMPLOYMENT'),
  P('{offer_date}'),
  P('Dear {candidate_first_name},'),
  P('We are delighted to offer you the position of {job_title} at {company_name} (the "Company"), reporting to {manager_name}, {manager_title}. {#is_remote}This is a remote position.{/is_remote}{^is_remote}You will be based at our {office_location} office.{/is_remote}'),
  H2('Start date'),
  P('Your anticipated start date is {start_date}, subject to the conditions below.'),
  H2('Compensation'),
  P('Your {pay_basis} salary will be {salary}, paid in accordance with the Company\'s standard payroll schedule and subject to applicable withholdings.'),
  P('{#has_bonus}You will be eligible for a discretionary annual bonus with a target of {bonus_target} of your base salary, based on Company and individual performance.{/has_bonus}'),
  P('{#has_equity}Subject to approval by the board of directors, you will be granted {equity_amount} under the Company\'s equity incentive plan, vesting over {vesting_years} years with a one-year cliff.{/has_equity}'),
  H2('Benefits'),
  P('You will be eligible for the following benefits, subject to the terms of each plan:'),
  new Paragraph({ children: [new TextRun('{#benefits}')] }),
  Bullet('{item}'),
  new Paragraph({ children: [new TextRun('{/benefits}')] }),
  P('You will accrue {pto_days} days of paid time off per year.'),
  H2('Conditions'),
  P('This offer is contingent on {#has_background_check}satisfactory completion of a background check and {/has_background_check}proof of your eligibility to work in {work_country}. Employment is {employment_terms}.'),
  P('Please confirm your acceptance by signing below and returning this letter by {response_deadline}.'),
  P('We look forward to working with you.'),
  P('Sincerely,'), P('{signatory_name}'), P('{signatory_title}, {company_name}'),
  P(''),
  P('ACCEPTED:'), P('____________________________'), P('{candidate_full_name}'), P('Date: ______________'),
]);


const contractor = doc([
  Title('INDEPENDENT CONTRACTOR AGREEMENT'),
  P('This Independent Contractor Agreement (the "Agreement") is made on {effective_date} between {client_name}, {client_address} (the "Client"), and {contractor_name}, {contractor_address} (the "Contractor").'),
  H('1. Services'),
  P('The Contractor will provide the following services (the "Services"): {services_description}. The Services begin on {start_date}{#has_end_date} and end on {end_date}{/has_end_date}{^has_end_date} and continue until either party ends this Agreement under section 6{/has_end_date}.'),
  H('2. Fees'),
  P('{#fee_hourly}The Client will pay the Contractor {hourly_rate} per hour for time spent on the Services{#has_hours_cap}, up to {hours_cap} hours per month unless the Client agrees otherwise in writing{/has_hours_cap}.{/fee_hourly}{#fee_fixed}The Client will pay the Contractor a fixed fee of {fixed_fee} for the Services.{/fee_fixed}'),
  P('The Contractor will invoice the Client {invoice_frequency}. Invoices are due within {payment_days} days of receipt.{#reimburse_expenses} The Client will reimburse reasonable, pre-approved expenses supported by receipts.{/reimburse_expenses}'),
  H('3. Independent contractor'),
  P('The Contractor is an independent contractor, not an employee, partner or agent of the Client. The Contractor decides how, when and where to perform the Services, provides their own equipment, and is responsible for their own taxes, insurance and benefits.'),
  H('4. Intellectual property'),
  P('{#client_owns_ip}All work product created by the Contractor for the Client under this Agreement belongs to the Client once paid for, and the Contractor assigns all rights in it to the Client.{/client_owns_ip}{^client_owns_ip}The Contractor keeps ownership of their work product and grants the Client a non-exclusive, perpetual licence to use it for the Client\'s business once paid for.{/client_owns_ip}'),
  H('5. Confidentiality'),
  P('The Contractor will keep the Client\'s non-public information confidential and use it only to perform the Services, during this Agreement and for {confidentiality_years} years afterwards.'),
  H('6. Termination'),
  P('Either party may end this Agreement with {notice_days} days\' written notice. The Client will pay for Services performed up to the end date.'),
  H('7. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  H('Signatures'),
  P('{client_name}'), P('By: ____________________________'), P('Name: {client_signatory}'), P(''),
  P('{contractor_name}'), P('Signature: ____________________________'),
]);

const sow = doc([
  Title('STATEMENT OF WORK'),
  P('Statement of Work number {sow_number}, dated {sow_date}, under the agreement between {client_name} (the "Client") and {provider_name} (the "Provider") dated {agreement_date}.'),
  H2('Project'),
  P('{project_name}: {project_summary}'),
  H2('Deliverables'),
  new Paragraph({ children: [new TextRun('{#deliverables}')] }),
  Bullet('{title}: {description} (due {due_date})'),
  new Paragraph({ children: [new TextRun('{/deliverables}')] }),
  H2('Timeline'),
  P('Work starts on {start_date} and is expected to finish by {end_date}.'),
  H2('Fees'),
  P('{#fixed_price}The total fixed price for this Statement of Work is {total_price}, invoiced {invoice_schedule}.{/fixed_price}{^fixed_price}Work is billed on a time-and-materials basis at {hourly_rate} per hour, with an estimated total of {estimated_total}.{/fixed_price}'),
  H2('Assumptions'),
  P('{assumptions}'),
  H2('Acceptance'),
  P('The Client will review each deliverable within {review_days} business days of delivery and either accept it or describe the changes needed.'),
  P(''),
  P('Accepted for {client_name}: ____________________________  Date: ______________'),
  P('Accepted for {provider_name}: ____________________________  Date: ______________'),
]);

const verification = doc([
  Title('EMPLOYMENT VERIFICATION LETTER'),
  P('{letter_date}'),
  P('To whom it may concern,'),
  P('This letter confirms that {employee_name} {#is_current}is employed{/is_current}{^is_current}was employed{/is_current} by {company_name} as {job_title}{#is_current} since {start_date}{/is_current}{^is_current} from {start_date} to {end_date}{/is_current}.'),
  P('{employee_first_name} {#is_current}works{/is_current}{^is_current}worked{/is_current} on a {employment_type} basis.'),
  P('{#include_salary}{employee_first_name}\'s current annual base salary is {salary}.{/include_salary}'),
  P('This letter is provided at the employee\'s request{#has_purpose} for the purpose of {purpose}{/has_purpose}. For further verification, please contact {contact_name} at {contact_email}.'),
  P('Sincerely,'), P('{signatory_name}'), P('{signatory_title}, {company_name}'),
]);

const demand = doc([
  Title('DEMAND FOR PAYMENT'),
  P('{letter_date}'),
  P('{debtor_name}'), P('{debtor_address}'),
  P('Re: Outstanding balance of {amount_due}{#has_invoice_number} (invoice {invoice_number}){/has_invoice_number}'),
  P('Dear {debtor_salutation},'),
  P('Our records show that {amount_due} for {goods_or_services} provided by {creditor_name} was due on {due_date} and remains unpaid.'),
  P('Please pay the full amount by {pay_by_date}. {payment_instructions}'),
  P('{#charges_interest}Under the terms agreed between us, interest of {interest_rate} is being added to the overdue balance.{/charges_interest}'),
  P('If you have already paid, please disregard this letter and send us the payment details so we can update our records. If you believe the amount is not owed, or you would like to agree a payment plan, please contact {contact_name} at {contact_email} before {pay_by_date}.'),
  P('{#mention_next_steps}If we do not receive payment or hear from you by that date, we may take further steps to recover the debt, which may include {next_steps}.{/mention_next_steps}'),
  P('Sincerely,'), P('{contact_name}'), P('{creditor_name}'),
]);


const unilateralNda = doc([
  Title('NON-DISCLOSURE AGREEMENT'),
  P('This Non-Disclosure Agreement (the "Agreement") is made on {effective_date} between {discloser_name}, {discloser_address} (the "Disclosing Party"), and {recipient_name}, {recipient_address} (the "Receiving Party").'),
  H('1. Purpose'),
  P('The Disclosing Party will share confidential information with the Receiving Party for the purpose of {purpose} (the "Purpose").'),
  H('2. Confidential Information'),
  P('"Confidential Information" means all non-public information the Disclosing Party shares in connection with the Purpose, in any form, that is marked confidential or that a reasonable person would understand to be confidential. It does not include information that is or becomes public through no fault of the Receiving Party, that the Receiving Party already lawfully knew, or that it develops independently.'),
  H('3. Obligations of the Receiving Party'),
  Numbered('Use the Confidential Information only for the Purpose.'),
  Numbered('Not disclose it to anyone except its employees and advisers who need to know it and are bound by similar confidentiality duties.'),
  Numbered('Protect it with at least reasonable care.'),
  Numbered('Return or destroy it on request{#certify_destruction} and confirm in writing that it has done so{/certify_destruction}.'),
  H('4. Term'),
  P('The obligations in this Agreement last for {term_years} years from the date above.'),
  H('5. No licence'),
  P('Nothing in this Agreement grants the Receiving Party any rights in the Confidential Information other than to use it for the Purpose.'),
  H('6. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  H('Signatures'),
  P('{discloser_name}'), P('By: ____________________________'), P('Name and title: {discloser_signatory}'), P(''),
  P('{recipient_name}'), P('By: ____________________________'), P('Name and title: {recipient_signatory}'),
]);

const consulting = doc([
  Title('CONSULTING AGREEMENT'),
  P('This Consulting Agreement is made on {effective_date} between {client_name} (the "Client") and {consultant_name} (the "Consultant").'),
  H('1. Engagement'),
  P('The Client engages the Consultant to provide advice and services relating to {engagement_scope} (the "Services"), starting on {start_date}.'),
  H('2. Deliverables'),
  new Paragraph({ children: [new TextRun('{#deliverables}')] }),
  Bullet('{title} by {due_date}'),
  new Paragraph({ children: [new TextRun('{/deliverables}')] }),
  H('3. Fees'),
  P('{#monthly_retainer}The Client will pay a monthly retainer of {retainer_amount}, invoiced in advance at the start of each month.{/monthly_retainer}{^monthly_retainer}The Client will pay {daily_rate} per day of Services, invoiced monthly in arrears.{/monthly_retainer} Invoices are payable within {payment_days} days.'),
  H('4. Relationship'),
  P('The Consultant is an independent contractor and is responsible for their own taxes, insurance and working arrangements.'),
  H('5. Confidentiality and ownership'),
  P('The Consultant will keep the Client\'s confidential information secret. Reports and materials produced specifically for the Client belong to the Client once paid for; the Consultant keeps their pre-existing know-how, methods and tools.'),
  H('6. Term and termination'),
  P('This Agreement continues until {end_date} unless either party ends it earlier with {notice_days} days\' written notice.'),
  H('7. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{client_name}: ____________________________'), P('{consultant_name}: ____________________________'),
]);

const termination = doc([
  Title('NOTICE OF TERMINATION OF EMPLOYMENT'),
  P('{letter_date}'),
  P('{employee_name}'), P('{employee_address}'),
  P('Dear {employee_first_name},'),
  P('This letter confirms that your employment with {company_name} as {job_title} will end on {termination_date}.'),
  P('{#has_reason}The reason for this decision is {termination_reason}.{/has_reason}'),
  P('{#notice_pay}You will receive pay in lieu of notice for {notice_period}.{/notice_pay}{^notice_pay}Your notice period is {notice_period}{#garden_leave}, and you will not be required to work during it{/garden_leave}.{/notice_pay}'),
  P('Your final pay, including any accrued but unused paid time off, will be paid on {final_pay_date}.{#has_severance} In addition, you will receive a severance payment of {severance_amount}, subject to the terms set out in a separate agreement.{/has_severance}'),
  P('Please return all company property, including {property_to_return}, by {return_by_date}.'),
  P('{#benefits_info}Information about your benefits after your employment ends, including any continuation options, will be sent to you separately.{/benefits_info}'),
  P('If you have questions, please contact {hr_contact_name} at {hr_contact_email}.'),
  P('Sincerely,'), P('{signatory_name}'), P('{signatory_title}, {company_name}'),
]);

const reference = doc([
  Title('LETTER OF REFERENCE'),
  P('{letter_date}'),
  P('To whom it may concern,'),
  P('I am pleased to provide this reference for {candidate_name}, who worked with me at {company_name} as {job_title} from {start_date} to {end_date}. I was {relationship} during this time.'),
  P('{candidate_first_name}\'s main responsibilities included {responsibilities}.'),
  P('{#has_strengths}In my experience, {candidate_first_name}\'s particular strengths are:{/has_strengths}'),
  new Paragraph({ children: [new TextRun('{#strengths}')] }),
  Bullet('{strength}'),
  new Paragraph({ children: [new TextRun('{/strengths}')] }),
  P('{#include_recommendation}I recommend {candidate_first_name} without reservation for {target_role}.{/include_recommendation}'),
  P('Please feel free to contact me at {referee_email}{#has_phone} or {referee_phone}{/has_phone} if you would like to discuss this further.'),
  P('Yours faithfully,'), P('{referee_name}'), P('{referee_title}, {company_name}'),
]);

const raise = doc([
  Title('SALARY INCREASE LETTER'),
  P('{letter_date}'),
  P('Dear {employee_first_name},'),
  P('I am pleased to confirm that your annual base salary will increase from {current_salary} to {new_salary}, effective {effective_date}.'),
  P('{#has_reason}This increase recognises {increase_reason}.{/has_reason}'),
  P('{#has_title_change}Your job title will also change to {new_job_title} from the same date.{/has_title_change}'),
  P('All other terms of your employment remain unchanged. The new salary will appear in your pay from {first_pay_date}.'),
  P('Thank you for your continued contribution to {company_name}.'),
  P('Kind regards,'), P('{signatory_name}'), P('{signatory_title}'),
]);

const internship = doc([
  Title('INTERNSHIP OFFER'),
  P('{offer_date}'),
  P('Dear {candidate_first_name},'),
  P('We are pleased to offer you an internship as {internship_title} in our {team_name} team at {company_name}, starting on {start_date} and ending on {end_date}.'),
  P('{#is_paid}You will be paid {pay_rate} {pay_basis}.{/is_paid}{^is_paid}This is an unpaid internship{#has_stipend}, with a stipend of {stipend_amount} towards expenses{/has_stipend}.{/is_paid}'),
  P('You will work {hours_per_week} hours per week{#is_remote}, remotely{/is_remote}{^is_remote}, at our {office_location} office{/is_remote}. Your supervisor will be {supervisor_name}.'),
  P('During the internship you will work on {learning_objectives}.'),
  P('{#academic_credit}We will provide any documentation your school requires for academic credit.{/academic_credit}'),
  P('Please confirm your acceptance by {response_deadline}.'),
  P('Welcome aboard,'), P('{signatory_name}'), P('{signatory_title}, {company_name}'),
]);

const service = doc([
  Title('SERVICE AGREEMENT'),
  P('This Service Agreement is made on {effective_date} between {provider_name} (the "Provider") and {customer_name} (the "Customer").'),
  H('1. Services'),
  P('The Provider will provide the following services: {services_description}.'),
  new Paragraph({ children: [new TextRun('{#service_items}')] }),
  Bullet('{item}: {price}'),
  new Paragraph({ children: [new TextRun('{/service_items}')] }),
  H('2. Payment'),
  P('The Customer will pay the Provider\'s invoices within {payment_days} days.{#late_fee} Late payments incur a fee of {late_fee_terms}.{/late_fee}{#deposit_required} A deposit of {deposit_amount} is payable on signing.{/deposit_required}'),
  H('3. Term'),
  P('This Agreement starts on {start_date} and {#auto_renews}renews automatically every {renewal_period} unless either party gives {notice_days} days\' notice.{/auto_renews}{^auto_renews}ends on {end_date}.{/auto_renews}'),
  H('4. Standard of work'),
  P('The Provider will perform the services with reasonable skill and care. The Customer will provide the access and information the Provider reasonably needs.'),
  H('5. Liability'),
  P('Each party\'s total liability under this Agreement is limited to the fees paid in the twelve months before the claim, except where the law does not allow liability to be limited.'),
  H('6. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{provider_name}: ____________________________'), P('{customer_name}: ____________________________'),
]);

const cease = doc([
  Title('CEASE AND DESIST'),
  P('{letter_date}'),
  P('{recipient_name}'), P('{recipient_address}'),
  P('Dear {recipient_salutation},'),
  P('We write on behalf of {sender_name} regarding {conduct_description}.'),
  P('{sender_name} {#is_ip_claim}owns the rights in {protected_work}, and this conduct infringes those rights.{/is_ip_claim}{^is_ip_claim}considers this conduct to be unlawful and harmful to its interests.{/is_ip_claim}'),
  P('We ask that you:'),
  new Paragraph({ children: [new TextRun('{#demands}')] }),
  Bullet('{demand}'),
  new Paragraph({ children: [new TextRun('{/demands}')] }),
  P('Please confirm in writing by {response_deadline} that you have done so.'),
  P('{#reserve_rights}If we do not receive a satisfactory response by that date, {sender_name} reserves all of its rights and remedies.{/reserve_rights}'),
  P('Nothing in this letter waives any of {sender_name}\'s rights, all of which are expressly reserved.'),
  P('Sincerely,'), P('{signatory_name}'), P('{signatory_title}'),
]);

const promissory = doc([
  Title('PROMISSORY NOTE'),
  P('Principal amount: {principal_amount}        Date: {note_date}'),
  P('For value received, {borrower_name} of {borrower_address} (the "Borrower") promises to pay {lender_name} of {lender_address} (the "Lender") the principal amount above{#charges_interest}, with interest at {interest_rate} per year{/charges_interest}.'),
  H2('Repayment'),
  P('{#pay_in_installments}The Borrower will repay the loan in {installment_count} {installment_frequency} instalments of {installment_amount}, starting on {first_payment_date}.{/pay_in_installments}{^pay_in_installments}The Borrower will repay the full amount{#charges_interest} with interest{/charges_interest} on or before {maturity_date}.{/pay_in_installments}'),
  H2('Prepayment'),
  P('The Borrower may repay all or part of the loan early without penalty.'),
  H2('Default'),
  P('If any payment is more than {grace_days} days late, the Lender may demand immediate payment of the full outstanding balance.'),
  H2('Governing law'),
  P('This note is governed by the laws of {governing_law}.'),
  P(''), P('Borrower: ____________________________  {borrower_name}'),
  P('{#has_witness}Witness: ____________________________  {witness_name}{/has_witness}'),
]);

const resignation = doc([
  Title('LETTER OF RESIGNATION'),
  P('{letter_date}'),
  P('Dear {manager_name},'),
  P('Please accept this letter as formal notice of my resignation from my position as {job_title} at {company_name}. My last working day will be {last_day}{#standard_notice}, in line with my notice period of {notice_period}{/standard_notice}.'),
  P('{#has_reason}I have decided to {resignation_reason}.{/has_reason}'),
  P('{#offer_handover}I will do everything I can to ensure a smooth handover, including {handover_plan}.{/offer_handover}'),
  P('{#thank}Thank you for the opportunities I have had during my time here. I have particularly valued {appreciation}.{/thank}'),
  P('Yours sincerely,'), P('{employee_name}'),
]);

const webDesign = doc([
  Title('WEB DESIGN AGREEMENT'),
  P('This Web Design Agreement is made on {effective_date} between {designer_name} (the "Designer") and {client_name} (the "Client").'),
  H('1. Project'),
  P('The Designer will design and build {project_description}. The site will include the following pages:'),
  new Paragraph({ children: [new TextRun('{#pages}')] }),
  Bullet('{page_name}: {page_notes}'),
  new Paragraph({ children: [new TextRun('{/pages}')] }),
  H('2. Timeline'),
  P('Work starts on {start_date} and the target launch date is {launch_date}. The Client will provide all text, images and logins the Designer needs by {content_deadline}; later delivery moves the launch date accordingly.'),
  H('3. Revisions'),
  P('The fee includes {revision_rounds} rounds of revisions to the approved design. Further changes, or work outside the pages listed above, are charged at {hourly_rate} per hour and agreed in writing first.'),
  H('4. Fees and payment'),
  P('The total fee is {total_fee}. {#has_deposit}A deposit of {deposit_amount} is due on signing and is not refundable once work has started; the balance is due on launch.{/has_deposit}{^has_deposit}The fee is due on launch.{/has_deposit} Invoices are payable within {payment_days} days.'),
  P('{#include_maintenance}After launch, the Designer will provide hosting support, updates and backups for {maintenance_fee} per month, cancellable by either party on 30 days\' notice.{/include_maintenance}'),
  H('5. Ownership'),
  P('When the fee has been paid in full, the Client owns the final design and the content created for the site. The Designer keeps ownership of its pre-existing code, tools and templates and grants the Client a perpetual licence to use them as part of the site.'),
  P('{#portfolio_use}The Designer may show the finished site in its portfolio.{/portfolio_use}'),
  H('6. Third-party items'),
  P('Fonts, stock images, plugins and hosting are licensed or paid for by the Client, on the terms of their providers.'),
  H('7. Termination'),
  P('Either party may end this Agreement with {notice_days} days\' written notice. The Client will pay for work done up to the end of the notice period.'),
  H('8. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{designer_name}: ____________________________'), P('{client_name}: ____________________________'),
]);

const graphicDesign = doc([
  Title('GRAPHIC DESIGN AGREEMENT'),
  P('This Graphic Design Agreement is made on {effective_date} between {designer_name} (the "Designer") and {client_name} (the "Client").'),
  H('1. Project'),
  P('The Designer will create {project_description}, including the following deliverables:'),
  new Paragraph({ children: [new TextRun('{#deliverables}')] }),
  Bullet('{item_name} ({file_formats}), due {due_date}'),
  new Paragraph({ children: [new TextRun('{/deliverables}')] }),
  H('2. Concepts and revisions'),
  P('The Designer will present {concept_count} initial concepts. The Client chooses one, and the fee includes {revision_rounds} rounds of revisions to it.'),
  H('3. Fees'),
  P('{#is_flat_fee}The fee for the project is {total_fee}.{/is_flat_fee}{^is_flat_fee}The Designer charges {hourly_rate} per hour, estimated at {estimated_hours} hours; the Designer will tell the Client before exceeding the estimate.{/is_flat_fee}{#has_deposit} A deposit of {deposit_amount} is due before work starts.{/has_deposit} Invoices are payable within {payment_days} days.'),
  H('4. Ownership'),
  P('{#transfer_copyright}On payment in full, the Designer assigns to the Client the copyright in the final approved designs. Concepts and drafts that were not chosen remain the Designer\'s.{/transfer_copyright}{^transfer_copyright}The Designer keeps the copyright and grants the Client an exclusive licence to use the final approved designs for {licence_scope}.{/transfer_copyright}'),
  H('5. Files'),
  P('{#include_source_files}The Designer will deliver the editable source files with the final designs.{/include_source_files}{^include_source_files}The Designer will deliver the final designs as exported files. Editable source files are available for an additional {source_file_fee}.{/include_source_files}'),
  P('{#portfolio_use}The Designer may show the work in its portfolio once it has been published by the Client.{/portfolio_use}'),
  H('6. Cancellation'),
  P('If the Client cancels the project, the Client will pay for work completed to date{#has_kill_fee} plus a cancellation fee of {kill_fee}{/has_kill_fee}.'),
  H('7. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{designer_name}: ____________________________'), P('{client_name}: ____________________________'),
]);

const photography = doc([
  Title('PHOTOGRAPHY AGREEMENT'),
  P('This Photography Agreement is made on {effective_date} between {photographer_name} (the "Photographer") and {client_name} (the "Client").'),
  H('1. The shoot'),
  P('The Photographer will photograph {shoot_description} on {shoot_date} at {shoot_location}, providing {coverage_hours} hours of coverage{#has_second_shooter} with a second photographer{/has_second_shooter}.'),
  H('2. What the Client receives'),
  P('The Photographer will deliver about {image_count} edited digital images through an online gallery within {delivery_days} days of the shoot.'),
  P('{#include_prints}The package also includes the following prints:{/include_prints}'),
  new Paragraph({ children: [new TextRun('{#include_prints}{#prints}')] }),
  Bullet('{print_quantity} × {print_size}'),
  new Paragraph({ children: [new TextRun('{/prints}{/include_prints}')] }),
  H('3. Fees and payment'),
  P('The total fee is {total_fee}. A retainer of {retainer_amount} is due on booking to reserve the date, and the balance is due {balance_due_days} days before the shoot.{#has_travel_fee} Travel beyond {travel_radius} is charged at {travel_rate}.{/has_travel_fee}'),
  H('4. Cancellation and rescheduling'),
  P('If the Client cancels less than {cancellation_days} days before the shoot, the retainer is not refunded. The Photographer will try to accommodate a new date, subject to availability.'),
  P('If the Photographer cannot attend because of illness or events beyond their control, they will try to arrange a suitable replacement; if they cannot, they will refund all payments received, and that refund is the limit of their liability.'),
  H('5. Copyright and use of the images'),
  P('The Photographer owns the copyright in the images. {#is_commercial}The Client may use the images for commercial purposes, limited to {usage_scope}.{/is_commercial}{^is_commercial}The Client may print, share and post the images for personal, non-commercial use.{/is_commercial}'),
  P('{#portfolio_use}The Photographer may use selected images in their portfolio and marketing.{/portfolio_use}'),
  H('6. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{photographer_name}: ____________________________'), P('{client_name}: ____________________________'),
]);

const socialMedia = doc([
  Title('SOCIAL MEDIA MANAGEMENT AGREEMENT'),
  P('This Social Media Management Agreement is made on {effective_date} between {manager_name} (the "Manager") and {client_name} (the "Client").'),
  H('1. Services'),
  P('The Manager will plan, create and schedule content for the Client on the following platforms:'),
  new Paragraph({ children: [new TextRun('{#platforms}')] }),
  Bullet('{platform_name}: {posts_per_week} posts per week'),
  new Paragraph({ children: [new TextRun('{/platforms}')] }),
  P('{#include_community_management}The Manager will also respond to comments and messages within {response_hours} business hours.{/include_community_management}'),
  P('{#include_paid_ads}The Manager will run paid campaigns within a monthly ad budget of {ad_budget}, which the Client pays directly to the platforms.{/include_paid_ads}'),
  H('2. Approvals'),
  P('The Manager will share planned content at least {approval_days} business days before it is published. Content the Client has not approved in time may be postponed.'),
  P('{#include_reports}The Manager will send a {report_frequency} report on reach, engagement and follower growth.{/include_reports}'),
  H('3. Fees'),
  P('The Client will pay {monthly_fee} per month, invoiced at the start of each month and payable within {payment_days} days.'),
  H('4. Accounts and content'),
  P('The Client owns its social media accounts. The Manager will use the access it is given only to provide the services, and will hand back or remove that access when this Agreement ends. Content created for the Client belongs to the Client once paid for.'),
  H('5. Results'),
  P('The Manager will use reasonable skill and care but does not guarantee any number of followers, level of engagement or sales.'),
  H('6. Term'),
  P('This Agreement starts on {start_date} and runs for a minimum of {minimum_months} months. After that it continues month to month until either party gives {notice_days} days\' written notice.'),
  H('7. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{manager_name}: ____________________________'), P('{client_name}: ____________________________'),
]);

const writing = doc([
  Title('FREELANCE WRITING AGREEMENT'),
  P('This Freelance Writing Agreement is made on {effective_date} between {writer_name} (the "Writer") and {client_name} (the "Client").'),
  H('1. Assignments'),
  P('The Writer will write the following pieces to the Client\'s brief:'),
  new Paragraph({ children: [new TextRun('{#assignments}')] }),
  Bullet('{piece_title}: about {word_count} words, due {due_date}, fee {piece_fee}'),
  new Paragraph({ children: [new TextRun('{/assignments}')] }),
  H('2. Revisions'),
  P('Each fee includes {revision_rounds} rounds of revisions, requested within {revision_window_days} days of delivery. Changes to the brief after writing has started may be charged as a new assignment.'),
  H('3. Originality'),
  P('The Writer confirms that the work will be original and will not knowingly infringe anyone else\'s rights{#disclose_ai_use}, and will tell the Client if AI tools were used to draft any part of it{/disclose_ai_use}.'),
  H('4. Payment'),
  P('The Writer will invoice each piece on delivery, and the Client will pay within {payment_days} days.{#has_kill_fee} If the Client cancels a piece after writing has started, the Client will pay {kill_fee_percent}% of its fee.{/has_kill_fee}'),
  H('5. Rights'),
  P('{#transfer_rights}On payment, the Writer assigns to the Client all rights in the finished piece.{/transfer_rights}{^transfer_rights}On payment, the Writer grants the Client {rights_granted}, and keeps all other rights.{/transfer_rights}'),
  P('{#include_byline}The Client will publish each piece under the Writer\'s name.{/include_byline}{^include_byline}The Client may publish the pieces without a byline.{/include_byline}'),
  H('6. Independent contractor'),
  P('The Writer is an independent contractor, not an employee of the Client, and is responsible for their own taxes.'),
  H('7. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{writer_name}: ____________________________'), P('{client_name}: ____________________________'),
]);

const video = doc([
  Title('VIDEO PRODUCTION AGREEMENT'),
  P('This Video Production Agreement is made on {effective_date} between {producer_name} (the "Producer") and {client_name} (the "Client").'),
  H('1. Project'),
  P('The Producer will produce {project_description}, delivering the following videos:'),
  new Paragraph({ children: [new TextRun('{#videos}')] }),
  Bullet('{video_title}: {video_length}, {video_format}'),
  new Paragraph({ children: [new TextRun('{/videos}')] }),
  H('2. Schedule'),
  P('Pre-production begins on {start_date} and filming takes place on {shoot_date}. The Producer will deliver a first cut within {first_cut_days} days of filming and the final videos by {delivery_date}.'),
  H('3. Revisions'),
  P('The fee includes {revision_rounds} rounds of edits to the first cut. Further edits are charged at {hourly_rate} per hour.'),
  H('4. Fees and expenses'),
  P('The total fee is {total_fee}.{#has_deposit} A deposit of {deposit_amount} is due on signing to secure the dates.{/has_deposit} Invoices are payable within {payment_days} days.'),
  P('{#include_expenses}Travel, equipment hire, location fees and talent are charged at cost with receipts. Any single expense over {expense_limit} needs the Client\'s approval first.{/include_expenses}'),
  H('5. Music, people and locations'),
  P('The Producer will use properly licensed music and obtain releases from anyone it casts. The Client is responsible for permissions for its own premises, staff and materials shown in the videos.'),
  H('6. Ownership'),
  P('On payment in full, the Client owns the final edited videos. {#include_raw_footage}The Producer will also deliver the raw footage.{/include_raw_footage}{^include_raw_footage}The Producer keeps the raw footage for {footage_retention_months} months and can supply it for an additional fee.{/include_raw_footage}'),
  P('{#portfolio_use}The Producer may show the finished videos in its portfolio once the Client has published them.{/portfolio_use}'),
  H('7. Cancellation'),
  P('If the Client cancels less than {cancellation_days} days before filming, the deposit is not refunded and the Client pays any costs already committed.'),
  H('8. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{producer_name}: ____________________________'), P('{client_name}: ____________________________'),
]);

const assistant = doc([
  Title('VIRTUAL ASSISTANT AGREEMENT'),
  P('This Virtual Assistant Agreement is made on {effective_date} between {assistant_name} (the "Assistant") and {client_name} (the "Client").'),
  H('1. Services'),
  P('The Assistant will provide remote administrative support, including:'),
  new Paragraph({ children: [new TextRun('{#tasks}')] }),
  Bullet('{task_description}'),
  new Paragraph({ children: [new TextRun('{/tasks}')] }),
  H('2. Hours and fees'),
  P('{#is_retainer}The Client books {monthly_hours} hours per month for {monthly_fee}, invoiced in advance. Unused hours do not carry over; extra hours are charged at {hourly_rate} per hour.{/is_retainer}{^is_retainer}The Assistant charges {hourly_rate} per hour, invoiced {invoice_frequency}.{/is_retainer} Invoices are payable within {payment_days} days.'),
  P('The Assistant is available {availability} ({time_zone}) and will reply to messages within {response_hours} business hours.'),
  H('3. Access and confidentiality'),
  P('The Client will share logins through a password manager where possible. The Assistant will keep the Client\'s information confidential, use its access only to provide the services, and hand back or remove all access when this Agreement ends.'),
  P('{#include_data_processing}Where the Assistant handles personal data for the Client, it will do so only on the Client\'s instructions, keep it secure and delete or return it at the end of the engagement.{/include_data_processing}'),
  H('4. Tools and expenses'),
  P('The Client provides any software subscriptions the work requires. Other expenses need the Client\'s approval in advance.'),
  H('5. Independent contractor'),
  P('The Assistant is an independent contractor, may work for other clients, and is responsible for their own taxes and equipment.'),
  H('6. Term'),
  P('This Agreement starts on {start_date} and continues until either party gives {notice_days} days\' written notice.'),
  H('7. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{assistant_name}: ____________________________'), P('{client_name}: ____________________________'),
]);

const eventPlanning = doc([
  Title('EVENT PLANNING AGREEMENT'),
  P('This Event Planning Agreement is made on {effective_date} between {planner_name} (the "Planner") and {client_name} (the "Client").'),
  H('1. The event'),
  P('The Planner will help plan {event_type} on {event_date} at {venue_name} for about {guest_count} guests.'),
  H('2. Services'),
  P('The Planner will provide the following services:'),
  new Paragraph({ children: [new TextRun('{#services}')] }),
  Bullet('{service_item}'),
  new Paragraph({ children: [new TextRun('{/services}')] }),
  P('{#include_day_of_coordination}On the day, the Planner will coordinate vendors and the schedule for up to {coordination_hours} hours.{/include_day_of_coordination}'),
  H('3. Fees'),
  P('{#is_percentage_fee}The Planner\'s fee is {fee_percentage}% of the total event budget, currently estimated at {event_budget}.{/is_percentage_fee}{^is_percentage_fee}The Planner\'s fee is {planning_fee}.{/is_percentage_fee} A retainer of {retainer_amount} is due on signing and is not refundable. The balance is due {balance_due_days} days before the event.'),
  H('4. Vendors and budget'),
  P('The Client contracts with and pays vendors directly. The Planner will recommend vendors in good faith but is not responsible for their performance, and will not commit the Client to any cost without the Client\'s approval.'),
  P('{#disclose_commissions}The Planner will tell the Client about any commission or referral fee it receives from a vendor.{/disclose_commissions}'),
  H('5. Cancellation and postponement'),
  P('If the Client cancels, the retainer is kept; if the Client cancels within {cancellation_days} days of the event, the full fee is due. If the event is postponed to a date within {reschedule_months} months, payments made are credited to the new date.'),
  H('6. Events beyond control'),
  P('Neither party is responsible for failure to perform caused by events beyond its reasonable control, such as severe weather, venue closure or government restrictions. In that case the parties will try to agree a new date, and payments made will be credited to it.'),
  H('7. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{planner_name}: ____________________________'), P('{client_name}: ____________________________'),
]);

const training = doc([
  Title('PERSONAL TRAINING AGREEMENT'),
  P('This Personal Training Agreement is made on {effective_date} between {trainer_name} (the "Trainer") and {client_name} (the "Client").'),
  H('1. Sessions'),
  P('{#is_package}The Client buys a package of {session_count} sessions for {package_price}, to be used within {package_weeks} weeks.{/is_package}{^is_package}Sessions cost {session_price} each.{/is_package} Each session lasts {session_length} minutes and takes place at {training_location}.'),
  H('2. Scheduling and cancellation'),
  P('Sessions cancelled with less than {cancellation_hours} hours\' notice count as used. If the Trainer cancels, the session will be rescheduled at no charge.'),
  H('3. Health'),
  P('The Client confirms that they know of no medical reason why they should not exercise, and will tell the Trainer about any injury, condition or medication that could affect training.{#requires_medical_clearance} Before the first session the Client will provide written clearance from a doctor.{/requires_medical_clearance}'),
  H('4. Risk'),
  P('The Client understands that exercise carries some risk of injury and agrees to follow the Trainer\'s instructions and stop if they feel unwell. Nothing in this Agreement limits the Trainer\'s liability for negligence where the law does not allow it to be limited.'),
  H('5. Results'),
  P('The Trainer will use reasonable skill and care but cannot guarantee any particular result.'),
  H('6. Payment'),
  P('Sessions and packages are paid in advance. {#refund_unused_sessions}If the Client cannot continue for medical reasons, unused sessions will be refunded.{/refund_unused_sessions}{^refund_unused_sessions}Packages are not refundable, but unused sessions can be transferred to another person with the Trainer\'s agreement.{/refund_unused_sessions}'),
  H('7. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{trainer_name}: ____________________________'), P('{client_name}: ____________________________'),
]);

const tutoring = doc([
  Title('TUTORING AGREEMENT'),
  P('This Tutoring Agreement is made on {effective_date} between {tutor_name} (the "Tutor") and {parent_name} (the "Parent") for tutoring of {student_name} (the "Student").'),
  H('1. Subjects and goals'),
  P('The Tutor will teach {subjects} at {grade_level} level. The goals are: {learning_goals}.'),
  H('2. Sessions'),
  P('The Tutor will provide {sessions_per_week} sessions per week of {session_length} minutes each, {#is_online}online using {video_platform}{/is_online}{^is_online}at {session_location}{/is_online}.'),
  H('3. Fees'),
  P('The fee is {hourly_rate} per hour, invoiced {invoice_frequency} and payable within {payment_days} days.'),
  H('4. Cancellation'),
  P('Sessions cancelled with less than {cancellation_hours} hours\' notice are charged in full, unless the Student is ill.'),
  P('{#include_progress_reports}The Tutor will send the Parent a {report_frequency} progress update.{/include_progress_reports}'),
  H('5. Safeguarding and conduct'),
  P('{#is_online}Online sessions will not be recorded without the Parent\'s written consent.{/is_online}{^is_online}A parent or another responsible adult will be available at the location during each session.{/is_online}{#has_background_check} The Tutor holds a current background check and will show it on request.{/has_background_check}'),
  P('The Tutor will help the Student learn but will not complete graded work for them.'),
  H('6. Term'),
  P('This Agreement starts on {start_date} and continues until either party gives {notice_days} days\' written notice.'),
  H('7. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{tutor_name}: ____________________________'), P('{parent_name}: ____________________________'),
]);

const reminder = doc([
  Title('{#is_final_notice}FINAL NOTICE BEFORE FURTHER ACTION{/is_final_notice}{^is_final_notice}PAYMENT REMINDER{/is_final_notice}'),
  P('{letter_date}'),
  P('{client_name}'), P('{client_address}'),
  P('Re: Invoice {invoice_number} for {amount_due}, due {due_date}'),
  P('Dear {client_salutation},'),
  P('{^is_final_notice}I hope all is well. This is a friendly reminder that invoice {invoice_number} for {amount_due}, for {services_description}, was due on {due_date} and has not been paid yet. It may simply have been missed, so a copy is attached.{/is_final_notice}'),
  P('{#is_final_notice}Invoice {invoice_number} for {amount_due}, for {services_description}, was due on {due_date} and remains unpaid despite our earlier reminders{#has_earlier_reminders} of {earlier_reminder_dates}{/has_earlier_reminders}.{/is_final_notice}'),
  P('{#has_partial_payment}Thank you for the {amount_paid} received so far. The balance still owed is {balance_due}.{/has_partial_payment}'),
  P('Please pay by {pay_by_date}. {payment_instructions}'),
  P('{#mention_late_fee}As set out in our terms, a late payment charge of {late_fee} applies to balances not paid by that date.{/mention_late_fee}'),
  P('{#is_final_notice}If we do not receive payment or hear from you by {pay_by_date}, we will {next_steps} without further notice. We would much rather settle this directly, so please contact us before then if there is a problem.{/is_final_notice}'),
  P('If you have already paid, thank you, and please send the payment details so we can match it. If something about the invoice is wrong, or you would like to agree a payment plan, please contact {contact_name} at {contact_email}.'),
  P('Kind regards,'), P('{contact_name}'), P('{business_name}'),
]);

const subcontractor = doc([
  Title('SUBCONTRACTOR AGREEMENT'),
  P('This Subcontractor Agreement is made on {effective_date} between {contractor_name}, {contractor_address} (the "Contractor"), and {subcontractor_name}, {subcontractor_address} (the "Subcontractor").'),
  H('1. Background'),
  P('The Contractor has agreed to provide services to {end_client_name} (the "Client") and engages the Subcontractor to perform part of that work.'),
  H('2. Services'),
  P('The Subcontractor will provide the following (the "Services"):'),
  new Paragraph({ children: [new TextRun('{#deliverables}')] }),
  Bullet('{deliverable_description}, due {deliverable_due_date}'),
  new Paragraph({ children: [new TextRun('{/deliverables}')] }),
  P('The Subcontractor will perform the Services with reasonable skill and care, on time, and to any standards the Contractor gives it in writing.{#must_follow_client_terms} The Contractor has shared the parts of its contract with the Client that apply to the Services, and the Subcontractor will comply with them as if it were the Contractor.{/must_follow_client_terms}'),
  H('3. Fees and payment'),
  P('{#is_fixed_fee}The Contractor will pay the Subcontractor a fixed fee of {fixed_fee} for the Services.{/is_fixed_fee}{^is_fixed_fee}The Contractor will pay the Subcontractor {hourly_rate} per hour, up to {max_hours} hours unless the Contractor agrees to more in writing.{/is_fixed_fee}'),
  P('The Subcontractor will invoice the Contractor {invoice_frequency}. The Contractor will pay each undisputed invoice within {payment_days} days of receiving it.{#pay_when_paid} If the Client has not yet paid the Contractor for the related work, the Contractor may delay payment until {days_after_client_payment} days after the Client pays, but never more than {longstop_days} days after the invoice date.{/pay_when_paid}'),
  P('{#reimburse_expenses}The Contractor will reimburse reasonable expenses that it approved in advance, supported by receipts.{/reimburse_expenses}'),
  H('4. Independent contractor'),
  P('The Subcontractor is an independent business, not an employee, partner or agent of the Contractor. It decides how to perform the Services, provides its own equipment, and is responsible for its own taxes and insurance. It may not pass the Services to anyone else without the Contractor\'s written consent.'),
  H('5. The Client relationship'),
  P('{#is_white_label}The Subcontractor will work as part of the Contractor\'s team, will not contact the Client about the project unless the Contractor agrees, and will pass any Client enquiries to the Contractor.{/is_white_label}'),
  P('{#include_non_solicitation}During this Agreement and for {non_solicit_months} months after it ends, the Subcontractor will not solicit the Client for, or accept from the Client, work similar to the Services without the Contractor\'s written consent.{/include_non_solicitation}'),
  H('6. Ownership of the work'),
  P('Once the Contractor has paid for it, all work the Subcontractor creates for the Services belongs to the Contractor, so that the Contractor can pass it to the Client, and the Subcontractor assigns all rights in it to the Contractor. {#portfolio_use}The Subcontractor may show the work in its portfolio once the Client has made it public, unless the Contractor says otherwise.{/portfolio_use}{^portfolio_use}The Subcontractor will not show or publish the work.{/portfolio_use}'),
  H('7. Confidentiality'),
  P('The Subcontractor will keep the Contractor\'s and the Client\'s non-public information confidential and use it only to perform the Services, during this Agreement and for {confidentiality_years} years afterwards.'),
  P('{#requires_insurance}The Subcontractor will hold {insurance_type} insurance with cover of at least {insurance_amount} while it performs the Services, and will show proof on request.{/requires_insurance}'),
  H('8. Ending this Agreement'),
  P('Either party may end this Agreement with {notice_days} days\' written notice. If the Client ends or reduces its project with the Contractor, the Contractor may end or reduce this Agreement to match by written notice. In every case the Contractor pays for Services properly performed up to the end date.'),
  H('9. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{contractor_name}: ____________________________'), P('{subcontractor_name}: ____________________________'),
]);

const retainer = doc([
  Title('RETAINER AGREEMENT'),
  P('This Retainer Agreement is made on {effective_date} between {provider_name}, {provider_address} (the "Provider"), and {client_name}, {client_address} (the "Client").'),
  H('1. Services'),
  P('Each month the Provider will be available to provide the following services (the "Services"):'),
  new Paragraph({ children: [new TextRun('{#services}')] }),
  Bullet('{service_description}'),
  new Paragraph({ children: [new TextRun('{/services}')] }),
  P('Work outside the Services, such as new projects, will be quoted separately before it starts.'),
  H('2. Retainer fee'),
  P('The Client will pay a monthly retainer of {monthly_fee}{#has_included_hours}, which covers up to {included_hours} hours of work each month{/has_included_hours}. The retainer is invoiced at the start of each month, in advance, and is payable within {payment_days} days.'),
  P('{#has_included_hours}{#hours_roll_over}Unused hours carry over to the following month only, and then expire.{/hours_roll_over}{^hours_roll_over}Unused hours do not carry over to the following month.{/hours_roll_over} Extra hours are charged at {overage_rate} per hour and need the Client\'s approval before the work starts.{/has_included_hours}'),
  P('The Provider may pause work while an invoice is more than {suspension_days} days overdue.{#charges_interest} Overdue invoices carry interest at {interest_rate} per year from the due date until paid.{/charges_interest}'),
  P('{#annual_fee_review}The Provider may change the retainer fee once a year by giving {fee_notice_days} days\' written notice.{/annual_fee_review}'),
  H('3. Availability'),
  P('The Provider will reply to requests within {response_hours} business hours and aims to complete routine requests within {turnaround_days} business days. {#includes_monthly_report}The Provider will send a short monthly report of the work done and the hours used.{/includes_monthly_report}'),
  H('4. Term'),
  P('This Agreement starts on {start_date}{#has_minimum_term} and runs for a minimum of {minimum_term_months} months{/has_minimum_term}. {#has_minimum_term}After that, either{/has_minimum_term}{^has_minimum_term}Either{/has_minimum_term} party may end it with {notice_days} days\' written notice. The retainer for the notice period remains payable.'),
  H('5. Ownership'),
  P('Work the Provider creates for the Client belongs to the Client once it has been paid for. The Provider keeps its own tools, methods and pre-existing materials, and grants the Client a licence to use any that are part of the work. {#portfolio_use}The Provider may show the work in its portfolio once it is public.{/portfolio_use}'),
  H('6. Confidentiality'),
  P('Each party will keep the other\'s non-public information confidential, during this Agreement and for {confidentiality_years} years afterwards.'),
  H('7. Independent contractor'),
  P('The Provider is an independent business, not an employee of the Client, and is responsible for its own taxes, equipment and insurance. The Provider may work for other clients.'),
  H('8. Governing law'),
  P('This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('{provider_name}: ____________________________'), P('{client_name}: ____________________________'),
]);

const mou = doc([
  Title('MEMORANDUM OF UNDERSTANDING'),
  P('This Memorandum of Understanding (the "MOU") is made on {effective_date} between {party_a_name}, {party_a_address} ("{party_a_short_name}"), and {party_b_name}, {party_b_address} ("{party_b_short_name}").'),
  H('1. Purpose'),
  P('This MOU records the parties\' shared understanding about {purpose}.'),
  H('2. What each party will do'),
  P('{party_a_short_name} will:'),
  new Paragraph({ children: [new TextRun('{#party_a_commitments}')] }),
  Bullet('{a_commitment}'),
  new Paragraph({ children: [new TextRun('{/party_a_commitments}')] }),
  P('{party_b_short_name} will:'),
  new Paragraph({ children: [new TextRun('{#party_b_commitments}')] }),
  Bullet('{b_commitment}'),
  new Paragraph({ children: [new TextRun('{/party_b_commitments}')] }),
  H('3. Costs'),
  P('{#has_shared_costs}The parties will share the costs of the activities in this MOU as follows: {cost_sharing_terms}{/has_shared_costs}{^has_shared_costs}Each party will pay its own costs of the activities in this MOU.{/has_shared_costs}'),
  H('4. Term'),
  P('This MOU takes effect on {effective_date} and continues until {end_date}, unless either party ends it earlier by written notice to the other. The parties may extend it by agreeing in writing.'),
  P('{#include_confidentiality}Each party will keep confidential any non-public information it receives from the other under this MOU, and use it only for the purpose above, during this MOU and for {confidentiality_years} years after it ends.{/include_confidentiality}'),
  H('5. Legal effect'),
  P('{^is_binding}This MOU is a statement of the parties\' intentions. Apart from this section, the section on costs{#include_confidentiality} and the confidentiality paragraph{/include_confidentiality}, which are binding, it does not create legal obligations, and either party may withdraw from the activities it describes. Any binding commitment will be set out in a separate written agreement signed by both parties.{/is_binding}{#is_binding}The parties intend this MOU to be a legally binding agreement between them.{/is_binding}'),
  H('6. Contacts'),
  P('{party_a_short_name}: {party_a_contact_name}, {party_a_contact_email}. {party_b_short_name}: {party_b_contact_name}, {party_b_contact_email}.'),
  H('7. Governing law'),
  P('This MOU is governed by the laws of {governing_law}.'),
  P(''), P('Signed for {party_a_name}: ____________________________  {party_a_signatory}'), P('Signed for {party_b_name}: ____________________________  {party_b_signatory}'),
]);

const loi = doc([
  P('{letter_date}'),
  P('{recipient_name}'), P('{seller_name}'), P('{seller_address}'),
  P('Re: Letter of intent to acquire {target_name}', { bold: true }),
  P('Dear {recipient_name},'),
  P('This letter sets out the main terms on which {buyer_name} (the "Buyer") proposes to {#is_share_purchase}buy all of the shares in{/is_share_purchase}{^is_share_purchase}buy the business and assets of{/is_share_purchase} {target_name} (the "Business") from {seller_name} (the "Seller").'),
  H2('Price'),
  P('The proposed price is {purchase_price}, to be paid {#is_paid_at_closing}in full at closing{/is_paid_at_closing}{^is_paid_at_closing}as follows: {payment_terms}{/is_paid_at_closing}.{#has_earn_out} Up to a further {earn_out_amount} will depend on the Business\'s performance after closing, on terms to be agreed in the definitive agreement.{/has_earn_out} The price assumes the Business is delivered free of debt and with a normal level of working capital.'),
  H2('Due diligence'),
  P('The Seller will give the Buyer and its advisers reasonable access to the Business\'s financial, legal, tax and operational records, premises and key staff. The Buyer expects to complete its review within {due_diligence_days} days of the date the Seller signs this letter.'),
  H2('Definitive agreement and closing'),
  P('The parties will negotiate in good faith a definitive purchase agreement containing the terms above and the warranties, indemnities and other terms usual for a transaction of this kind. The target closing date is {target_closing_date}. Closing will depend on:'),
  new Paragraph({ children: [new TextRun('{#conditions}')] }),
  Bullet('{condition}'),
  new Paragraph({ children: [new TextRun('{/conditions}')] }),
  P('{#include_exclusivity}For {exclusivity_days} days after the Seller signs this letter, the Seller will not solicit, encourage or negotiate any other offer to buy the Business or any significant part of it, and will tell the Buyer promptly if it receives one.{/include_exclusivity}'),
  H2('Confidentiality and costs'),
  P('Each party will keep this letter and all information it receives about the other confidential{#has_existing_nda}, as set out in the non-disclosure agreement between them dated {nda_date}{/has_existing_nda}. Each party will pay its own costs, whether or not the transaction goes ahead.'),
  H2('Legal effect'),
  P('Apart from the {#include_exclusivity}exclusivity, {/include_exclusivity}confidentiality and costs paragraphs and this paragraph, which are binding, this letter is not a legally binding agreement. Neither party is obliged to complete the transaction unless and until a definitive agreement is signed. This letter is governed by the laws of {governing_law}.'),
  P('This proposal expires if the Seller has not signed and returned a copy of this letter by {offer_expiry_date}.'),
  P('Yours sincerely,'),
  P(''), P('____________________________'), P('{buyer_signatory}, for {buyer_name}'),
  P(''), P('Agreed and accepted by {seller_name}:'), P('____________________________   Date: ______________'),
]);

const billOfSale = doc([
  Title('BILL OF SALE'),
  P('Date of sale: {sale_date}'),
  H2('Seller'),
  P('{seller_name}, {seller_address}'),
  H2('Buyer'),
  P('{buyer_name}, {buyer_address}'),
  H2('The item sold'),
  P('The Seller sells and transfers to the Buyer the following (the "Item"): {item_description}'),
  P('{#is_vehicle}Vehicle: {vehicle_year} {vehicle_make} {vehicle_model}, colour {vehicle_colour}, vehicle identification number (VIN) {vehicle_vin}, odometer reading {odometer_reading}. To the best of the Seller\'s knowledge the odometer reading is the actual distance the vehicle has travelled{#has_odometer_discrepancy}, except that {odometer_note}{/has_odometer_discrepancy}.{/is_vehicle}'),
  H2('Price and payment'),
  P('The price for the Item is {sale_price}, payable by {how_paid}. {#is_paid_in_full}The Seller confirms that it has received the full price.{/is_paid_in_full}{^is_paid_in_full}The Buyer paid {deposit_amount} on the date of sale and will pay the balance of {balance_amount} on or before {balance_due_date}.{/is_paid_in_full}'),
  H2('Ownership'),
  P('The Seller confirms that the Seller owns the Item, has the right to sell it, and that it is free of any loan, lien or other claim{#has_disclosed_liens}, except: {lien_details}{/has_disclosed_liens}. Ownership of the Item passes to the Buyer {#is_paid_in_full}on the date of sale{/is_paid_in_full}{^is_paid_in_full}when the price has been paid in full{/is_paid_in_full}.'),
  H2('Condition'),
  P('{#is_as_is}The Buyer has had the opportunity to inspect the Item and accepts it "as is", with all faults. The Seller gives no warranty about its condition, except as to ownership above.{/is_as_is}{^is_as_is}The Seller gives the following warranty about the Item\'s condition: {warranty_terms}{/is_as_is}'),
  P(''), P('Seller: ____________________________  {seller_name}   Date: ______________'),
  P('Buyer: ____________________________  {buyer_name}   Date: ______________'),
  P('{#has_witness}Witness: ____________________________  {witness_name}{/has_witness}'),
  P('{#needs_notary}Notary acknowledgment: State/County of ______________. Signed before me on ______________ by the person(s) named above. Notary public: ____________________________  My commission expires: ______________{/needs_notary}'),
]);

const loan = doc([
  Title('LOAN AGREEMENT'),
  P('This Loan Agreement is made on {agreement_date} between {lender_name}, {lender_address} (the "Lender"), and {borrower_name}, {borrower_address} (the "Borrower").'),
  H('1. The loan'),
  P('The Lender will lend the Borrower {loan_amount} (the "Loan"), paid to the Borrower on {disbursement_date} by {transfer_method}.{#has_stated_purpose} The Borrower will use the Loan only for {loan_purpose}.{/has_stated_purpose}'),
  H('2. Interest'),
  P('{#charges_interest}Interest accrues on the unpaid balance at {interest_rate} per year, calculated daily on a 365-day year, from the date the Loan is paid to the Borrower until it is repaid. If that rate is higher than the maximum rate the law allows, the maximum lawful rate applies instead.{/charges_interest}{^charges_interest}The Loan is interest-free.{/charges_interest}'),
  H('3. Repayment'),
  P('{#pay_in_installments}The Borrower will repay the Loan{#charges_interest} with interest{/charges_interest} in {installment_count} {installment_frequency} instalments of {installment_amount}, starting on {first_payment_date}, with any remaining balance due on {maturity_date}.{/pay_in_installments}{^pay_in_installments}The Borrower will repay the Loan{#charges_interest} with interest{/charges_interest} in one payment on or before {maturity_date}.{/pay_in_installments} Payments will be made to: {lender_payment_details}'),
  P('The Borrower may repay all or part of the Loan early without penalty.{#charges_interest} Early payments are applied first to interest due and then to the balance.{/charges_interest}'),
  P('{#charges_late_fee}If a payment is more than {grace_days} days late, the Borrower will also pay a late fee of {late_fee}, to the extent permitted by law.{/charges_late_fee}'),
  H('4. Security and guarantee'),
  P('{#is_secured}To secure repayment, the Borrower grants the Lender a security interest in the following property: {collateral_description}. Until the Loan is repaid in full, the Borrower will keep that property in good condition and will not sell, give away or borrow against it without the Lender\'s written consent.{/is_secured}{^is_secured}The Loan is unsecured.{/is_secured}'),
  P('{#has_guarantor}{guarantor_name}, {guarantor_address} (the "Guarantor"), guarantees that the Borrower will pay every amount due under this Agreement, and will pay any such amount on demand if the Borrower does not.{/has_guarantor}'),
  H('5. Default'),
  P('The Borrower is in default if a payment is more than {default_days} days late, if the Borrower becomes insolvent or bankrupt, or if anything the Borrower told the Lender to obtain the Loan was materially untrue. If the Borrower is in default, the Lender may, by written notice, require immediate repayment of the whole unpaid balance{#charges_interest} and interest{/charges_interest}.{#include_collection_costs} The Borrower will also pay the Lender\'s reasonable costs of collecting overdue amounts, including legal fees, to the extent permitted by law.{/include_collection_costs}'),
  H('6. General'),
  P('This Agreement is the entire agreement between the parties about the Loan. Any change must be in writing and signed by both parties. If any part of this Agreement cannot be enforced, the rest remains in effect. This Agreement is governed by the laws of {governing_law}.'),
  P(''), P('Lender: ____________________________  {lender_name}'), P('Borrower: ____________________________  {borrower_name}'),
  P('{#has_guarantor}Guarantor: ____________________________  {guarantor_name}{/has_guarantor}'),
]);

mkdirSync('samples', { recursive: true });
for (const [file, d] of [['memorandum-of-understanding.docx', mou], ['letter-of-intent.docx', loi], ['bill-of-sale.docx', billOfSale], ['loan-agreement.docx', loan], ['payment-reminder-letter.docx', reminder], ['subcontractor-agreement.docx', subcontractor], ['retainer-agreement.docx', retainer], ['video-production-contract.docx', video], ['virtual-assistant-agreement.docx', assistant], ['event-planning-contract.docx', eventPlanning], ['personal-training-agreement.docx', training], ['tutoring-agreement.docx', tutoring], ['web-design-contract.docx', webDesign], ['graphic-design-contract.docx', graphicDesign], ['photography-contract.docx', photography], ['social-media-management-contract.docx', socialMedia], ['freelance-writing-contract.docx', writing], ['mutual-nda.docx', nda], ['engagement-letter.docx', engagement], ['offer-letter.docx', offer], ['independent-contractor-agreement.docx', contractor], ['statement-of-work.docx', sow], ['employment-verification-letter.docx', verification], ['payment-demand-letter.docx', demand], ['one-way-nda.docx', unilateralNda], ['consulting-agreement.docx', consulting], ['employment-termination-letter.docx', termination], ['reference-letter.docx', reference], ['salary-increase-letter.docx', raise], ['internship-offer-letter.docx', internship], ['service-agreement.docx', service], ['cease-and-desist-letter.docx', cease], ['promissory-note.docx', promissory], ['resignation-letter.docx', resignation]]) {
  writeFileSync(`samples/${file}`, await deterministic(await Packer.toBuffer(d)));
  console.log('wrote samples/' + file);
}
